package com.example.rocnikovaprace;

public enum GameStatus {
        UVOD, OKNO,SPAT, ROZHOVORSESTAROSTOUA, DVERE, ROZHOVORSESTAROSTOUB,ROZHOVORSESTAROSTOUB_A, ROZHOVORSESTAROSTOUBA_B, KAPITOLA2, GAMEOVER,
}
