package com.example.rocnikovaprace;

public enum GameStatus {
        UVOD, OKNO, MENU, SPAT, ROZHOVORSESTAROSTOUA, ROZHOVORSESTAROSTOUA_A, ROZHOVORSESTAROSTOUA_B, DVERE, ROZHOVORSESTAROSTOUB,ROZHOVORSESTAROSTOUB_A, ROZHOVORSESTAROSTOUB_B, ROZHOVORSESTAROSTOUBA_B, ROZHOVORSESTAROSTOUBA_A,
}
