package com.example.rocnikovaprace;

public enum GameStatus {
        UVOD, OKNO,SPAT, ROZHOVORSESTAROSTOUA, DVERE, ROZHOVORSESTAROSTOUB,ROZHOVORSESTAROSTOUB_A, ROZHOVORSESTAROSTOUB_B, ROZHOVORSESTAROSTOUBA_B, ROZHOVORSESTAROSTOUBA_A, KAPITOLA2, GAMEOVER,
}
